/**
 * This file is autogenerated by the deployment workflow.
 * For local (chainId 31337) deployments, create CreditScoreEngine.local.ts
 * (gitignored) using the same shape and it will be merged in at module load.
 *
 * Non-local deployments live in REMOTE below keyed by chainId.
 * Import: `import { CreditScoreEngine } from "~~/contracts/CreditScoreEngine";`
 */
import type { ContractDeployment } from "~~/utils/contract";

export const CreditScoreEngineABI = [
  // ── submitFactors ────────────────────────────────────────────────────
  {
    type: "function",
    name: "submitFactors",
    inputs: [
      { name: "paymentHistory", type: "bytes32", internalType: "externalEuint64" },
      { name: "dti", type: "bytes32", internalType: "externalEuint64" },
      { name: "creditAge", type: "bytes32", internalType: "externalEuint64" },
      { name: "utilization", type: "bytes32", internalType: "externalEuint64" },
      { name: "inputProof", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // ── authorizeLender ──────────────────────────────────────────────────
  {
    type: "function",
    name: "authorizeLender",
    inputs: [{ name: "lender", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // ── revokeLender ─────────────────────────────────────────────────────
  {
    type: "function",
    name: "revokeLender",
    inputs: [{ name: "lender", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // ── getMyScore ───────────────────────────────────────────────────────
  {
    type: "function",
    name: "getMyScore",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "euint64" }],
    stateMutability: "view",
  },
  // ── requestScore (lender) ────────────────────────────────────────────
  {
    type: "function",
    name: "requestScore",
    inputs: [{ name: "borrower", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bytes32", internalType: "euint64" }],
    stateMutability: "view",
  },
  // ── meetsThreshold ───────────────────────────────────────────────────
  {
    type: "function",
    name: "meetsThreshold",
    inputs: [
      { name: "borrower", type: "address", internalType: "address" },
      { name: "threshold", type: "uint64", internalType: "uint64" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "ebool" }],
    stateMutability: "nonpayable",
  },
  // ── view helpers ──────────────────────────────────────────────────────
  {
    type: "function",
    name: "hasSubmitted",
    inputs: [{ name: "borrower", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasScore",
    inputs: [{ name: "borrower", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isLenderAuthorized",
    inputs: [
      { name: "borrower", type: "address", internalType: "address" },
      { name: "lender", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  // ── confidentialProtocolId (ZamaEthereumConfig) ────────────────────
  {
    type: "function",
    name: "confidentialProtocolId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  // ── Events ────────────────────────────────────────────────────────────
  {
    type: "event",
    name: "FactorsSubmitted",
    inputs: [{ name: "borrower", type: "address", indexed: true }],
  },
  {
    type: "event",
    name: "LenderAuthorized",
    inputs: [
      { name: "borrower", type: "address", indexed: true },
      { name: "lender", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "LenderRevoked",
    inputs: [
      { name: "borrower", type: "address", indexed: true },
      { name: "lender", type: "address", indexed: true },
    ],
  },
  // ── Errors ─────────────────────────────────────────────────────────────
  {
    type: "error",
    name: "FactorsNotSubmitted",
    inputs: [{ name: "borrower", type: "address" }],
  },
  {
    type: "error",
    name: "ScoreNotComputed",
    inputs: [{ name: "borrower", type: "address" }],
  },
  {
    type: "error",
    name: "NotAuthorized",
    inputs: [
      { name: "lender", type: "address" },
      { name: "borrower", type: "address" },
    ],
  },
  { type: "error", name: "ZamaProtocolUnsupported", inputs: [] },
  {
    type: "error",
    name: "SenderNotAllowedToUseHandle",
    inputs: [
      { name: "handle", type: "bytes32" },
      { name: "sender", type: "address" },
    ],
  },
] as const;

// ── Local sidecar (filled by deploy:localhost) ──────────────────────────────
let LOCAL: Partial<Record<number, ContractDeployment>> = {};
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const mod = require("./CreditScoreEngine.local");
  LOCAL = mod.CreditScoreEngine ?? {};
} catch {
  /* not present yet – that's fine */
}

// Placeholder – replace address + deployedOnBlock after `pnpm deploy:sepolia`
const REMOTE: Record<number, ContractDeployment> = {
  11155111: {
    address: "0x02DF09970f298c26B703637A863c98D850258a70",
    abi: CreditScoreEngineABI,
    deployedOnBlock: 0,
  },
};

export const CreditScoreEngine = {
  ...REMOTE,
  ...LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
